### ISSUE TITLE
Custom Images

### ISSUE THREAD

**Issue by cannyboy** [AlexeyBelezeko/TBIconTransitionKit#3]
Creating custom TBAnimationButtonState images, perhaps using - https://github.com/cparnot/ASCIImage - would be nice. @cparnot mentions - https://github.com/cparnot/ASCIImage/issues/12#issuecomment-99024489 - the idea of using the same characters to indicate the points to animate between.

**Comment by AlexeyBelezeko** [comment]
Hi @cannyboy . It's great idea, but in this small kit I use custom animation and transition states for all animated transition. So if we will create icons with ASCII we will lose smooth and pixel perfect =)
