### ISSUE TITLE
 TBAnimationButtonStatePlus to TBAnimationButtonStateCross

### ISSUE THREAD

**Issue by xtcan** [AlexeyBelezeko/TBIconTransitionKit#6]
Hello, there is something wrong if i set the current state is TBAnimationButtonStatePlus and transform to TBAnimationButtonStateCross

**Comment by AlexeyBelezeko** [comment]
Hi. Sorry for my late answer. I found a bug in my code. I'll fixed it asap. I have the same issue for minus to cross transition.

**Comment by AlexeyBelezeko** [comment]
Thank you. I've fixed this bug.
